---
- name: "Restart gitea"
  ansible.builtin.service:
    name: gitea
    state: restarted
  when: (ansible_service_mgr == "systemd") or (ansible_service_mgr == "openrc")

- name: "Reload systemd"
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_service_mgr == "systemd"

- name: "Restart fail2ban"
  ansible.builtin.service:
    name: fail2ban
    state: restarted
  when: (ansible_service_mgr == "systemd") or (ansible_service_mgr == "openrc")

- name: Enable service gitea
  ansible.builtin.service:
    name: gitea
    enabled: yes
  when: ansible_service_mgr == "openrc"
